name: IntegrationTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: SetupShellScript
      run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
      
    - name: FullInstallMimixBox
      run: make build
           sudo install -v -m 0755 -D mimixbox /usr/local/bin/.
           mimixbox --full-install /usr/local/bin/
      
    - name: IntegrationTest
      run: make it
