name: IntegrationTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: SetupShellScript
      run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
      
    - name: Build
      run: make build
      
    - name: CreateSymbolicLink
      run: make full-install
      
    - name: IntegrationTest
      run: make it
