name: IntegrationTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  integration_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: SetupShellScript
      run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
      
    - name: Build
      run: make build

    - name: InstallMimixBox
      run: sudo install -v -m 0755 -D mimixbox /usr/local/bin/.
      
    - name: CreateSymbolicLink
      run: mimixbox --full-install /usr/local/bin/

    - name: InstallDos2unix
      run: sudo apt-get update && sudo apt-get install dos2unix
      
    - name: IntegrationTest
      run: export PATH=$PATH:/usr/local/bin && make it
